stages:
  - deploy

push to master:
  stage: deploy
  only:
    - develop
  script:
    - chmod +x scripts/git-push
    - scripts/git-push https://github.com/amensouissi/solidarity.git
  when: on_success