stages:
  - deploy

push to master:
  stage: deploy
  only:
    - develop
  script:
    - /bin/bash scripts/git-push https://amensouissi:$GITHUB_ACCESS_TOKEN@github.com/amensouissi/solidarity.git
  when: on_success

  