language: python
python:
  - "3.6"
sudo: required
dist: trusty
services:
  - postgresql
addons:
  ssh_known_hosts: localhost
  postgresql: "9.5"
  node: "6.13.0"
  yarn: "1.9.2"
git:
  depth: 100
cache:
  pip: true
  directories:
    - solidarity/static/node_modules  
before_install:
  - psql -c 'create database solidarity_test;' -U postgres
  - sudo apt-get update
  - npm install --global webpack@3.5.5
  - pip3 install --disable-pip-version-check --no-cache-dir setuptools==32.2.0 && pip3 uninstall -y six || true
install:
  - python3 bootstrap.py
  - bin/buildout
  - virtualenv -p python3 venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - alembic -c travis.ini upgrade head
  - cd solidarity/static
  - yarn install --ignore-engines
env:
  - TO_TEST=BACKEND
  - TO_TEST=FRONTEND
script:
  - if [ "$TO_TEST" = "FRONTEND" ]; then npm test; fi
  - if [ "$TO_TEST" = "FRONTEND" ]; then npm run eslint; fi
  - if [ "$TO_TEST" = "FRONTEND" ]; then npm run flow; fi
  - if [ "$TO_TEST" = "FRONTEND" ]; then npm run stylelint; fi
  - if [ "$TO_TEST" = "FRONTEND" ]; then npm run build >/dev/null; fi
  - if [ "$TO_TEST" = "FRONTEND" ]; then ls -l build/bundle.js; fi
  - cd ../..
  - if [ "$TO_TEST" = "BACKEND" ]; then bin/test -s solidarity; fi
notifications:
on_failure: always