#!/bin/bash -e

source_branch=$1
target_branch=$2

if [ -z "$SSH_PRIVATE_KEY" ]; then
	>&2 echo "Set SSH_PRIVATE_KEY environment variable"
	exit 1
fi

mkdir -p ~/.ssh
echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa
ssh-keyscan -H "gitlab.com" >> ~/.ssh/known_hosts

git remote set-url origin https://github.com/amensouissi/solidarity.git
git merge ${target_branch:-master}
git checkout ${target_branch:-master}
git merge ${source_branch:-origin/develop}
git push --force
exit 0